Repository swcamp-be15-baksal/be15-2nd-baksal-gulhan, pull requests merged in 2025-04, with the labels that each got.

#12 Feat: ApiResponse 파일 생성
  src/main/java/com/hanhwa_tae/gulhan/common/dto/ApiResponse.java
  src/main/java/com/hanhwa_tae/gulhan/common/dto/exam.java
Labels: 🤖 기능

#28 feat: 유저 회원가입 어노테이션 개발
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/service/AuthService.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/domain/aggregate/RefreshToken.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/domain/repository/AuthRepository.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/infrastructure/repository/exam.java
  src/main/java/com/hanhwa_tae/gulhan/config/exam.java
  src/main/java/com/hanhwa_tae/gulhan/user/annotation/ValidBirth.java
  src/main/java/com/hanhwa_tae/gulhan/user/annotation/ValidEmail.java
  src/main/java/com/hanhwa_tae/gulhan/user/annotation/ValidPhone.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/controller/UserCommandController.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/controller/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/GenderType.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/request/UserCreateRequest.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/request/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandService.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/Rank.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/RankName.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/User.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/UserInfo.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/repository/UserRepository.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/repository/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/infrastructure/JpaUserRepository.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/infrastructure/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/validator/BirthValidator.java
  src/main/java/com/hanhwa_tae/gulhan/user/validator/EmailValidator.java
  src/main/java/com/hanhwa_tae/gulhan/user/validator/PhoneValidator.java
  src/main/resources/application.yml
Labels: 🤖 기능

#41 feat: JWT 회원가입 개발 & 이메일 인증
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/service/AuthService.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/domain/aggregate/RefreshToken.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/domain/repository/AuthRepository.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/infrastructure/repository/exam.java
  src/main/java/com/hanhwa_tae/gulhan/config/exam.java
  src/main/java/com/hanhwa_tae/gulhan/packages/command/domain/aggregate/Package.java
  src/main/java/com/hanhwa_tae/gulhan/user/annotation/ValidBirth.java
  src/main/java/com/hanhwa_tae/gulhan/user/annotation/ValidEmail.java
  src/main/java/com/hanhwa_tae/gulhan/user/annotation/ValidPhone.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/controller/UserCommandController.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/controller/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/UserCreateDTO.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/UserInfoCreateDTO.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/request/UserCreateRequest.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/request/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandService.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandServiceImpl.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/GenderType.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/LoginType.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/Rank.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/RankName.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/RankType.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/RedisUser.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/User.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/UserInfo.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/repository/UserInfoRepository.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/repository/UserRepository.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/repository/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/infrastructure/JpaUserInfoRepository.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/infrastructure/JpaUserRepository.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/infrastructure/RedisUserRepository.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/infrastructure/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/mapper/UserMapper.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/mapper/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/validator/BirthValidator.java
  src/main/java/com/hanhwa_tae/gulhan/user/validator/EmailValidator.java
  src/main/java/com/hanhwa_tae/gulhan/user/validator/PhoneValidator.java
  src/main/java/com/hanhwa_tae/gulhan/utils/EmailUtil.java
  src/main/resources/application.yml
  src/main/resources/mappers/user/UserMapper.xml
Labels: 🤖 기능

#42 feat: JWT 로그인 개발
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/controller/AuthCommandController.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/dto/response/TokenResponse.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/service/AuthCommandService.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/service/AuthCommandServiceImpl.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/service/AuthService.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/domain/aggregate/RefreshToken.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/domain/repository/AuthRepository.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/infrastructure/repository/RedisAuthRepository.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/infrastructure/repository/exam.java
  src/main/java/com/hanhwa_tae/gulhan/auth/exam.java
  src/main/java/com/hanhwa_tae/gulhan/auth/query/controller/AuthQueryController.java
  src/main/java/com/hanhwa_tae/gulhan/auth/query/dto/request/LoginRequest.java
  src/main/java/com/hanhwa_tae/gulhan/auth/query/dto/response/UserDto.java
  src/main/java/com/hanhwa_tae/gulhan/auth/query/service/AuthQueryService.java
  src/main/java/com/hanhwa_tae/gulhan/auth/query/service/AuthQueryServiceImpl.java
  src/main/java/com/hanhwa_tae/gulhan/packages/command/domain/aggregate/Package.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/controller/UserCommandController.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/GenderType.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/UserCreateDTO.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/UserInfoCreateDTO.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/request/UserCreateRequest.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandService.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandServiceImpl.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/GenderType.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/Rank.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/RankName.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/RankType.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/RedisUser.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/User.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/UserInfo.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/repository/UserInfoRepository.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/infrastructure/JpaUserInfoRepository.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/infrastructure/JpaUserRepository.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/infrastructure/RedisUserRepository.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/controller/UserQueryController.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/controller/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/dto/request/LoginRequestUserRequest.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/dto/request/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/dto/response/LoginRequestUserResponse.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/dto/response/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/mapper/UserMapper.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/mapper/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/service/UserQueryService.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/service/UserQueryServiceImpl.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/service/examp.java
  src/main/java/com/hanhwa_tae/gulhan/user/validator/PhoneValidator.java
  src/main/java/com/hanhwa_tae/gulhan/utils/EmailUtil.java
  src/main/java/com/hanhwa_tae/gulhan/utils/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
  src/main/resources/mappers/user/UserMapper.xml
Labels: 🤖 기능

#45 feat: 에러코드 생성 및 에러코드 기입
  src/main/java/com/hanhwa_tae/gulhan/common/exception/BusinessException.java
  src/main/java/com/hanhwa_tae/gulhan/common/exception/ErrorCode.java
  src/main/java/com/hanhwa_tae/gulhan/common/exception/ErrorResponse.java
  src/main/java/com/hanhwa_tae/gulhan/common/exception/GlobalExceptionHandler.java
  src/main/java/com/hanhwa_tae/gulhan/common/exception/exam.java
Labels: 🤖 기능

#47 feat: Access Token 갱신 구현
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/controller/AuthCommandController.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/dto/request/RefreshTokenRequest.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/service/AuthCommandService.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/service/AuthCommandServiceImpl.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/service/CustomUserDetailService.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/domain/aggregate/RefreshToken.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/domain/aggregate/model/CustomUserDetail.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/domain/repository/AuthRepository.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/infrastructure/repository/RedisAuthRepository.java
  src/main/java/com/hanhwa_tae/gulhan/auth/query/controller/AuthQueryController.java
  src/main/java/com/hanhwa_tae/gulhan/auth/query/dto/response/AccessTokenResponse.java
  src/main/java/com/hanhwa_tae/gulhan/auth/query/service/AuthQueryService.java
  src/main/java/com/hanhwa_tae/gulhan/auth/query/service/AuthQueryServiceImpl.java
  src/main/java/com/hanhwa_tae/gulhan/common/exception/ErrorCode.java
  src/main/java/com/hanhwa_tae/gulhan/common/exception/GlobalExceptionHandler.java
  src/main/java/com/hanhwa_tae/gulhan/config/SecurityConfig.java
  src/main/java/com/hanhwa_tae/gulhan/utils/jwt/CustomAccessDeniedHandler.java
  src/main/java/com/hanhwa_tae/gulhan/utils/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/com/hanhwa_tae/gulhan/utils/jwt/JwtAuthenticationFilter.java
  src/main/java/com/hanhwa_tae/gulhan/utils/jwt/JwtErrorResponse.java
  src/main/java/com/hanhwa_tae/gulhan/utils/jwt/JwtTokenProvider.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: 🤖 기능

#61 feat: 유저 개인 정보 조회 & 수정
  src/main/java/com/hanhwa_tae/gulhan/Be152ndBaksalGulhanApplication.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/controller/AuthCommandController.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/service/AuthCommandService.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/service/AuthCommandServiceImpl.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/service/CustomUserDetailService.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/domain/aggregate/RefreshToken.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/domain/aggregate/model/CustomUserDetail.java
  src/main/java/com/hanhwa_tae/gulhan/auth/query/controller/AuthQueryController.java
  src/main/java/com/hanhwa_tae/gulhan/auth/query/service/AuthQueryService.java
  src/main/java/com/hanhwa_tae/gulhan/auth/query/service/AuthQueryServiceImpl.java
  src/main/java/com/hanhwa_tae/gulhan/common/exception/ErrorCode.java
  src/main/java/com/hanhwa_tae/gulhan/common/exception/GlobalExceptionHandler.java
  src/main/java/com/hanhwa_tae/gulhan/common/exception/custom/UnAuthorizationException.java
  src/main/java/com/hanhwa_tae/gulhan/config/RedisConfig.java
  src/main/java/com/hanhwa_tae/gulhan/config/SecurityConfig.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/controller/UserCommandController.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/UserCreateDTO.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/request/UpdateUserInfoRequest.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandService.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandServiceImpl.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/User.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/UserInfo.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/repository/UserInfoRepository.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/repository/UserRepository.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/controller/UserQueryController.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/dto/response/UserInfoResponse.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/mapper/UserMapper.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/service/UserQueryService.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/service/UserQueryServiceImpl.java
  src/main/java/com/hanhwa_tae/gulhan/utils/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/com/hanhwa_tae/gulhan/utils/jwt/JwtAuthenticationFilter.java
  src/main/java/com/hanhwa_tae/gulhan/utils/jwt/JwtTokenProvider.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: 🤖 기능

#70 fix: 유저 엔티티 username 변경
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/UserCreateDTO.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/request/UserCreateRequest.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandServiceImpl.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/User.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/dto/response/UserInfoResponse.java
Labels: 🐞 버그, ⛏️ 수정

#67 Feat/dashboard: 대시보드 구현
  src/main/java/com/hanhwa_tae/gulhan/cart/command/domain/aggregate/Order.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/command/application/controller/DashboardCommandController.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/command/application/dto/request/OrderUpdateRequest.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/command/application/service/DashboardCommandService.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/command/domain/repository/JpaOrderRepository.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/controller/DashboardQueryController.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/request/DashboardDailySearchRequest.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/request/DashboardGoodsSearchRequest.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/request/DashboardMonthlySearchRequest.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/request/DashboardOrderSearchRequest.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/request/DashboardPackageSearchRequest.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/response/DailyRevenueDTO.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/response/DailyRevenueListResponse.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/response/GoodsQuantityDTO.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/response/GoodsQuantityListResponse.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/response/MonthlyRevenueDTO.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/response/MonthlyRevenueListResponse.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/response/OrderAllListDTO.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/response/OrderAllListResponse.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/response/PackageQuantityDTO.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/dto/response/PackageQuantityListResponse.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/mapper/DashboardQueryMapper.java
  src/main/java/com/hanhwa_tae/gulhan/dashboard/query/service/DashboardQueryService.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/controller/UserCommandController.java
  src/main/resources/mappers/dashboard/DashboardMapper.xml
Labels: 🤖 기능

#30 feat: 조건별 장소 검색 기능 구현, 지역 목록 조회 기능 구현
  src/main/java/com/hanhwa_tae/gulhan/place/command/domain/aggregate/CategoryType.java
  src/main/java/com/hanhwa_tae/gulhan/place/command/domain/aggregate/Place.java
  src/main/java/com/hanhwa_tae/gulhan/place/exam.java
  src/main/java/com/hanhwa_tae/gulhan/place/query/controller/AreaQueryController.java
  src/main/java/com/hanhwa_tae/gulhan/place/query/controller/PlaceQueryController.java
  src/main/java/com/hanhwa_tae/gulhan/place/query/dto/request/AreaSearchRequest.java
  src/main/java/com/hanhwa_tae/gulhan/place/query/dto/request/PlaceSearchRequest.java
  src/main/java/com/hanhwa_tae/gulhan/place/query/dto/response/AreaDto.java
  src/main/java/com/hanhwa_tae/gulhan/place/query/dto/response/AreaListResponse.java
  src/main/java/com/hanhwa_tae/gulhan/place/query/dto/response/PlaceDto.java
  src/main/java/com/hanhwa_tae/gulhan/place/query/dto/response/PlaceListResponse.java
  src/main/java/com/hanhwa_tae/gulhan/place/query/mapper/AreaMapper.java
  src/main/java/com/hanhwa_tae/gulhan/place/query/mapper/PlaceMapper.java
  src/main/java/com/hanhwa_tae/gulhan/place/query/service/AreaQueryService.java
  src/main/java/com/hanhwa_tae/gulhan/place/query/service/PlaceQueryService.java
  src/main/resources/mappers/area/AreaMapper.xml
  src/main/resources/mappers/place/PlaceMapper.xml
Labels: 🤖 기능

#81 feat: 비밀번호 변경 구현
  src/main/java/com/hanhwa_tae/gulhan/common/exception/ErrorCode.java
  src/main/java/com/hanhwa_tae/gulhan/place/query/service/PlaceQueryService.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/controller/UserCommandController.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/request/ChangeUserPasswordRequest.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandService.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandServiceImpl.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/repository/UserRepository.java
Labels: 🤖 기능

#92 feat: 전체 등급 목록 조회 구현
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/dto/request/KakaoAdditionalInfoRequest.java
  src/main/java/com/hanhwa_tae/gulhan/auth/command/application/service/KakaoAuthService.java
  src/main/java/com/hanhwa_tae/gulhan/cart/command/application/controller/CartCommandController.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/controller/UserQueryController.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/dto/RankDTO.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/dto/response/RankInfoResponse.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/mapper/UserMapper.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/service/UserQueryService.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/service/UserQueryServiceImpl.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: 🤖 기능

#85 feat : 회원 탈퇴
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/controller/UserCommandController.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandService.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandServiceImpl.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/aggregate/User.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/dto/RankDTO.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/mapper/UserMapper.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: 🤖 기능

#75 feat: 비밀번호 찾기 구현
  src/main/java/com/hanhwa_tae/gulhan/config/SecurityConfig.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/controller/UserCommandController.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/dto/request/UserFindPasswordRequest.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandService.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/application/service/UserCommandServiceImpl.java
  src/main/java/com/hanhwa_tae/gulhan/user/command/domain/repository/UserRepository.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/mapper/UserMapper.java
  src/main/java/com/hanhwa_tae/gulhan/utils/RandomStringGenerator.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: 🤖 기능

#94 Feat: 회원 패키지/기념품 구매내역 조회
  src/main/java/com/hanhwa_tae/gulhan/cart/command/domain/aggregate/OrderHistory.java
  src/main/java/com/hanhwa_tae/gulhan/common/exception/ErrorCode.java
  src/main/java/com/hanhwa_tae/gulhan/user/me/query/controller/MyPageQueryController.java
  src/main/java/com/hanhwa_tae/gulhan/user/me/query/dto/GoodsOrderHistoryDTO.java
  src/main/java/com/hanhwa_tae/gulhan/user/me/query/dto/PackageOrderHistoryDTO.java
  src/main/java/com/hanhwa_tae/gulhan/user/me/query/mapper/MyPageMapper.java
  src/main/java/com/hanhwa_tae/gulhan/user/me/query/service/MyPageQueryService.java
  src/main/resources/mappers/user/me/MyPageMapper.xml
Labels: 🤖 기능

#98 refactor: /myPage /me 코드 통일
  src/main/java/com/hanhwa_tae/gulhan/user/me/query/controller/MyPageQueryController.java
  src/main/java/com/hanhwa_tae/gulhan/user/me/query/mapper/MyPageMapper.java
  src/main/java/com/hanhwa_tae/gulhan/user/me/query/service/MyPageQueryService.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/controller/UserQueryController.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/mapper/UserMapper.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/service/UserQueryService.java
  src/main/java/com/hanhwa_tae/gulhan/user/query/service/UserQueryServiceImpl.java
  src/main/resources/mappers/user/UserMapper.xml
  src/main/resources/mappers/user/me/MyPageMapper.xml
Labels: ⛏️ 수정

#102 feat: Spring Config 설정
  src/main/java/com/hanhwa_tae/gulhan/common/exception/ErrorCode.java
  src/main/java/com/hanhwa_tae/gulhan/config/SecurityConfig.java
  src/main/java/com/hanhwa_tae/gulhan/utils/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/com/hanhwa_tae/gulhan/utils/jwt/JwtAuthenticationFilter.java
  src/main/java/com/hanhwa_tae/gulhan/utils/jwt/JwtTokenProvider.java
Labels: 🤖 기능

#114 feat: user/controller 테스트 코드 작성
  second-server/src/main/java/com/hanhwa_tae/secondserver/config/SwaggerConfig.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/service/UserCommandServiceImpl.java
  second-server/src/test/java/com/hanhwa_tae/secondserver/annotation/WithCustomMockUser.java
  second-server/src/test/java/com/hanhwa_tae/secondserver/user/command/application/controller/UserCommandControllerTest.java
  second-server/src/test/java/com/hanhwa_tae/secondserver/user/query/controller/UserQueryControllerTest.java
Labels: ✔️ 테스트

#125 test: auth 테스트 코드 작성
  second-server/src/test/java/com/hanhwa_tae/secondserver/auth/query/controller/AuthQueryControllerTest.java
Labels: ✔️ 테스트

#124 test: 장소 테스트
  first-server/src/main/java/com/hanhwa_tae/firstserver/place/query/dto/request/AreaSearchRequest.java
  first-server/src/test/java/com/hanhwa_tae/firstserver/place/query/controller/AreaQueryControllerTest.java
  first-server/src/test/java/com/hanhwa_tae/firstserver/place/query/controller/PlaceQueryControllerTest.java
Labels: ✔️ 테스트

#122 test: 지역 목록 검색 테스트
  first-server/src/main/java/com/hanhwa_tae/firstserver/place/query/dto/request/AreaSearchRequest.java
  first-server/src/test/java/com/hanhwa_tae/firstserver/place/query/controller/AreaQueryControllerTest.java
Labels: ✔️ 테스트

#134 test: 유저 서비스 테스트코드 작성
  second-server/src/main/java/com/hanhwa_tae/secondserver/auth/command/application/service/AuthService.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/auth/query/service/AuthQueryServiceImpl.java
  second-server/src/test/java/com/hanhwa_tae/secondserver/auth/command/application/service/AuthCommandServiceImplTest.java
  second-server/src/test/java/com/hanhwa_tae/secondserver/auth/query/service/AuthQueryServiceImplTest.java
  second-server/src/test/java/com/hanhwa_tae/secondserver/user/command/application/service/UserCommandServiceImplTest.java
Labels: ✔️ 테스트

#135 Refactor: 결제 취소 기능 수정
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/application/controller/GetPayInfoController.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/application/controller/RefundController.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/application/controller/SuccessFailController.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/application/controller/SuccessPaymentController.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/application/controller/TossPaymentController.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/application/dto/request/CancelRequestDto.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/application/dto/request/CreateOrderRequest.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/application/dto/request/CreateRefundRequest.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/application/dto/response/CreateOrderResponse.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/application/service/PaymentService.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/application/service/RefundCommandService.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/domain/aggregate/Redispayinfo.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/domain/repository/GoodsPaymentRepository.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/domain/repository/PackagesPaymentRepository.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/domain/repository/RefundRepository.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/infrastructure/repository/JpaGoodsPaymentRepository.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/infrastructure/repository/JpaPackagesPaymentRepository.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/infrastructure/repository/JpaRefundRepository.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/command/infrastructure/repository/RedisPayInfoRepository.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/query/controller/SearchItemController.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/query/dto/request/examp.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/query/dto/response/OrderDetailResponse.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/query/dto/response/OrderHistoryDetailResponse.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/query/dto/response/OrderResponse.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/query/dto/response/RefundResponse.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/query/dto/response/RefundResponseDetail.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/query/mapper/PaymentMapper.java
  first-server/src/main/java/com/hanhwa_tae/firstserver/payment/query/service/SearchPaymentService.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/auth/command/application/service/AuthService.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/auth/query/service/AuthQueryServiceImpl.java
  second-server/src/test/java/com/hanhwa_tae/secondserver/auth/command/application/service/AuthCommandServiceImplTest.java
  second-server/src/test/java/com/hanhwa_tae/secondserver/auth/query/service/AuthQueryServiceImplTest.java
  second-server/src/test/java/com/hanhwa_tae/secondserver/user/command/application/service/UserCommandServiceImplTest.java
Labels: ⛏️ 수정

#136 refactor: 2서버 명칭 변경
  gateway/src/main/resources/application.yml
  second-server/src/main/java/com/hanhwa_tae/secondserver/dashboard/command/domain/repository/JpaOrderRepository.java
  second-server/src/main/resources/mappers/cart/CartMapper.xml
Labels: ⛏️ 수정

#142 feat: 배송 현황 조회
  second-server/build.gradle
  second-server/src/main/java/com/hanhwa_tae/secondserver/common/exception/ErrorCode.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/query/controller/DeliveryQueryController.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/query/controller/examp.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/query/dto/request/DeliveryInfoRequest.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/delivery/query/service/DeliveryQueryService.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/security/SecurityConfig.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/DeliveryStateCode.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/TrackResponse.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/response/DeliveryStateResponse.java
  second-server/src/test/java/com/hanhwa_tae/secondserver/delivery/query/service/DeliveryQueryServiceTest.java
Labels: 🤖 기능

#144 fix: 유저 기능 수정
  second-server/build.gradle
  second-server/src/main/java/com/hanhwa_tae/secondserver/common/exception/ErrorCode.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/common/exception/GlobalExceptionHandler.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/notice/command/application/controller/NoticeCommandController.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/annotation/ValidPassword.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/annotation/ValidUserId.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/controller/UserCommandController.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/request/UserCreateRequest.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/request/UserFindPasswordRequest.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/dto/request/UserVerifyFindPasswordRequest.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/service/UserCommandService.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/application/service/UserCommandServiceImpl.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/domain/aggregate/RedisUserPassword.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/command/infrastructure/RedisUserPasswordRepository.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/validator/PasswordValidator.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/user/validator/UserIdValidator.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/utils/EmailUtil.java
  second-server/src/main/java/com/hanhwa_tae/secondserver/utils/image/controller/ImageController.java
Labels: ⛏️ 수정
